In [3]:
import urllib3
import json
import pandas as pd
from bs4 import BeautifulSoup
import requests
import re

In [6]:

df = pd.read_csv('../prj_sns_trend_private/cleaned_cheeseball.csv')
df.drop([df.columns[0]],axis=1, inplace=True)
df

,title,date,cleaned_content
0,애주가TV참PDBHC 치즈볼 긴장해야 할거같습니다전국의 치즈볼이 씨가 마르겠네요\n...,2020-04-02,TV PDBHC 주가 치즈볼 긴장 전국 치즈볼 마르 영상 대박
1,애주가TV참PDBHC 치즈볼 긴장해야 할거같습니다여러분이 드시는 치킨 프랜차이즈 치...,2020-04-02,TV PDBHC 주가 치즈볼 긴장 치킨 프랜차이즈 치즈볼 자체 생산 외주 통해 제품...
2,애주가TV참PDBHC 치즈볼 긴장해야 할거같습니다이런 컨텐츠 참 좋은거 같아요 우...,2020-04-02,TV PDBHC 주가 치즈볼 긴장 컨텐츠 우리나라 대기업 여러가지 집중 중소기업 지면
3,애주가TV참PDBHC 치즈볼 긴장해야 할거같습니다503 8700 더 바삭한\n555...,2020-04-02,TV PDBHC 주가 치즈볼 긴장 바삭 푸드 썬리취 마니커 크림
4,애주가TV참PDBHC 치즈볼 긴장해야 할거같습니다811 최종평가,2020-04-02,TV PDBHC 주가 치즈볼 긴장 최종 평가
...,...,...,...
18774,연휴가 끝나서 힘들고 지칠 때 멕시카나치킨 을 찾아주세요 매콤단짠 뿌리고치킨 에 ...,2020-01-28,연휴 멕시 카나 치킨 아주 매콤 뿌리 고치 쫀득 더블 치즈볼 이면
18775,배달의민족 순수치킨 3000원 할인,2020-09-18,배달의민족 순수 치킨 할인
18776,금요일은 배달의민족 순수치킨 3000원 할인,2020-09-25,금요일 배달의민족 순수 치킨 할인
18777,또래오래 목우촌 배달의민족 쿠폰 프로모션 치킨 이번 주 금토일 치킨파티 각 쉿 6월...,2020-06-05,또래오래 우촌 배달의민족 쿠폰 프로모션 치킨 금토일 치킨 파티 일요일 배민 또래오래
18778,순수치킨이 새로 쓰는 치킨의정석 가성비가성비갓성비순수치킨,2020-09-15,순수 치킨 치킨 의정 성비 가성 비갓 성비 순수 치킨

In [7]:

#-*- coding:utf-8 -*-


#// 언어 분석 기술(구어)
openApiURL = "http://aiopen.etri.re.kr:8000/WiseNLU_spoken"
 
accessKey = "285a98de-eb7a-4292-a3e0-d36f5219be67"
analysisCode = "ner"

In [8]:

text = df['cleaned_content'][115]

#text += "네 안녕하세요 홍길동 교숩니다"+;

In [9]:

requestJson = {
    "access_key": accessKey,
    "argument": {
        "text": text,
        "analysis_code": analysisCode
    }
}
 
http = urllib3.PoolManager()
response = http.request(
    "POST",
    openApiURL,
    headers={"Content-Type": "application/json; charset=UTF-8"},
    body=json.dumps(requestJson)
)

res_data = str(response.data,"utf-8")

In [10]:
#JSON파일을 DATAFRAME으로 변경하기 위한 과정

In [12]:
json_load = json.loads(res_data)

In [13]:
json_load.keys()
#이후로 하나씩 추적

dict_keys(['result', 'return_object'])

In [14]:
#리스트 안에 딕셔너리{키:값}이 여러개면 그 리스트를 DATAFRAME으로 만들면 아래처럼 됨
print(json_load['return_object']['sentence'][0]['NE'])
df_new = pd.DataFrame(json_load['return_object']['sentence'][0]['NE'])
df_new

[{'id': 0.0, 'text': '커플', 'type': 'CV_RELATION', 'begin': 0.0, 'end': 0.0, 'weight': 0.435388, 'common_noun': 0.0}, {'id': 1.0, 'text': '커플', 'type': 'CV_RELATION', 'begin': 1.0, 'end': 1.0, 'weight': 0.445776, 'common_noun': 0.0}, {'id': 2.0, 'text': '치즈볼', 'type': 'CV_FOOD', 'begin': 2.0, 'end': 3.0, 'weight': 0.475058, 'common_noun': 0.0}, {'id': 3.0, 'text': '치즈볼', 'type': 'CV_FOOD', 'begin': 9.0, 'end': 10.0, 'weight': 0.680717, 'common_noun': 0.0}, {'id': 4.0, 'text': '치즈볼', 'type': 'CV_FOOD', 'begin': 12.0, 'end': 13.0, 'weight': 0.466818, 'common_noun': 0.0}, {'id': 5.0, 'text': '소연', 'type': 'PS_NAME', 'begin': 14.0, 'end': 14.0, 'weight': 0.18644, 'common_noun': 0.0}, {'id': 6.0, 'text': '치즈볼', 'type': 'CV_FOOD', 'begin': 15.0, 'end': 16.0, 'weight': 0.602705, 'common_noun': 0.0}, {'id': 7.0, 'text': '치즈볼', 'type': 'CV_FOOD', 'begin': 24.0, 'end': 24.0, 'weight': 0.362203, 'common_noun': 0.0}, {'id': 8.0, 'text': '형', 'type': 'CV_RELATION', 'begin': 26.0, 'end': 26.0, 'weight': 0.714811, 'common_noun': 0.0}, {'id': 9.0, 'text': '소연', 'type': 'PS_NAME', 'begin': 28.0, 'end': 28.0, 'weight': 0.143117, 'common_noun': 0.0}, {'id': 10.0, 'text': '여우', 'type': 'AM_MAMMALIA', 'begin': 29.0, 'end': 29.0, 'weight': 0.185939, 'common_noun': 0.0}, {'id': 11.0, 'text': '간식 햄스터 신기 치즈볼', 'type': 'CV_FOOD_STYLE', 'begin': 30.0, 'end': 34.0, 'weight': 0.181826, 'common_noun': 0.0}, {'id': 12.0, 'text': '뿌링소스', 'type': 'CV_FOOD', 'begin': 35.0, 'end': 36.0, 'weight': 0.136513, 'common_noun': 0.0}, {'id': 13.0, 'text': '대리', 'type': 'CV_POSITION', 'begin': 40.0, 'end': 40.0, 'weight': 0.438212, 'common_noun': 0.0}]

      id           text           type  begin   end    weight  common_noun
0    0.0             커플    CV_RELATION    0.0   0.0  0.435388          0.0
1    1.0             커플    CV_RELATION    1.0   1.0  0.445776          0.0
2    2.0            치즈볼        CV_FOOD    2.0   3.0  0.475058          0.0
3    3.0            치즈볼        CV_FOOD    9.0  10.0  0.680717          0.0
4    4.0            치즈볼        CV_FOOD   12.0  13.0  0.466818          0.0
5    5.0             소연        PS_NAME   14.0  14.0  0.186440          0.0
6    6.0            치즈볼        CV_FOOD   15.0  16.0  0.602705          0.0
7    7.0            치즈볼        CV_FOOD   24.0  24.0  0.362203          0.0
8    8.0              형    CV_RELATION   26.0  26.0  0.714811          0.0
9    9.0             소연        PS_NAME   28.0  28.0  0.143117          0.0
10  10.0             여우    AM_MAMMALIA   29.0  29.0  0.185939          0.0
11  11.0  간식 햄스터 신기 치즈볼  CV_FOOD_STYLE   30.0  34.0  0.181826          0.0
12  12.0           뿌링소스        CV_FOOD   35.0  36.0  0.136513          0.0
13  13.0             대리    CV_POSITION   40.0  40.0  0.438212          0.0

In [112]:
#이걸로 원하는 TYPE의 TITLE 뽑아내기
for i in range(len(df_new)):
    if df_new['type'][i] == 'CV_RELATION':
        print(df_new['text'][i])

커플
커플
형

In [72]:
df_json.head()

                 result return_object
DCT                   0
category              0
category_weight       0             0
doc_id                0
entity                0            []

In [29]:
print(type(response))

<class 'urllib3.response.HTTPResponse'>